apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-function-info-collector
  labels:
    app: network-function-info-collector
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: network-function-info-collector
  template:
    metadata:
      labels:
        app: network-function-info-collector
    spec:
      containers:
      - name: scanner
        image: maxlou05/network_function_info_collector:v2.15
